### ISSUE TITLE
Prompt message error still appear after pressing muscle tension filter type:

### ISSUE THREAD

**Issue by kingcoen390** [abuebola/sensobox#58]

**Comment by kingcoen390** [comment]
easy fix: change band edges "0 19 20 150 151 128"  to "0 19 20 50 100 128" as the values must be in increasing order and cannot surpass the sampling frequency of 128 Hz

**Comment by niroigen** [comment]
I had to make some changes because muscle tremor is from 20-150 Hz, so now it's fixed.
